### ISSUE TITLE
Add to poggit

### ISSUE THREAD

**Issue by Shadow-87** [NaufalBlaze/CalculatorUI#4]
Hello!
Thank you for your good plugin.
Do you request it in poggit?
I saw you put it in poggit-ci but I don't know you requested or no.
If you don't request it, please request. Your plugin doesn't have any problems and if you request it, it well accept. Thank you.
Sorry for bad English 😅

**Comment by NaufalBlaze** [comment]
CalculatorUI Not Approved In Poggit 😭

**Comment by Shadow-87** [comment]
Oh, why? An email must have been sent to you explaining why the plugin was rejected. Your plugin is good.

**Comment by NaufalBlaze** [comment]
Yes, I Also Don't Know Why I Disagree, Thx You:)
